/*
 * Generated by Bluespec Compiler, version 2014.07.A (build 34078, 2014-07-30)
 * 
 * On Thu May  3 20:30:46 -03 2018
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkBoxMuller_h__
#define __mkBoxMuller_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkWellPRNG.h"


/* Class declaration for the mkBoxMuller module */
class MOD_mkBoxMuller : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_cycle;
  MOD_Fifo<tUInt64> INST_fCheck;
  MOD_Reg<tUInt8> INST_flag;
  MOD_Reg<tUWide> INST_randtuple;
  MOD_mkWellPRNG INST_rgn1;
  MOD_mkWellPRNG INST_rgn2;
  MOD_Fifo<tUInt64> INST_sqrtfxm_fRequest;
  MOD_Fifo<tUWide> INST_sqrtfxm_fResponse;
  MOD_Fifo<tUInt8> INST_sqrtfxm_fShift;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fFirst;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_0;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_1;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_10;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_11;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_12;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_13;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_14;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_15;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_16;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_17;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_18;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_19;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_2;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_20;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_21;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_22;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_23;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_24;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_25;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_26;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_27;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_28;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_29;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_3;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_30;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_31;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_32;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_4;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_5;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_6;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_7;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_8;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fNext_9;
  MOD_Fifo<tUInt64> INST_sqrtfxm_sqrt_fRequest;
  MOD_Fifo<tUWide> INST_sqrtfxm_sqrt_fResponse;
  MOD_Wire<tUInt8> INST_testFSM_abort;
  MOD_Reg<tUInt8> INST_testFSM_start_reg;
  MOD_Reg<tUInt8> INST_testFSM_start_reg_1;
  MOD_Wire<tUInt8> INST_testFSM_start_reg_2;
  MOD_Wire<tUInt8> INST_testFSM_start_wire;
  MOD_Reg<tUInt8> INST_testFSM_state_can_overlap;
  MOD_Reg<tUInt8> INST_testFSM_state_fired;
  MOD_Wire<tUInt8> INST_testFSM_state_fired_1;
  MOD_ConfigReg<tUInt8> INST_testFSM_state_mkFSMstate;
  MOD_Wire<tUInt8> INST_testFSM_state_overlap_pw;
  MOD_Wire<tUInt8> INST_testFSM_state_set_pw;
  MOD_Reg<tUInt64> INST_valsqrIn;
  MOD_Reg<tUInt64> INST_valsqrOut;
 
 /* Constructor */
 public:
  MOD_mkBoxMuller(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUInt8 PORT_EN_initialize;
  tUInt8 PORT_EN_get;
  tUInt32 PORT_initialize_s1;
  tUInt32 PORT_initialize_s2;
  tUInt64 PORT_get_val;
  tUInt8 PORT_RDY_initialize;
  tUWide PORT_get;
  tUInt8 PORT_RDY_get;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_get;
  tUInt8 DEF_WILL_FIRE_initialize;
  tUInt8 DEF_WILL_FIRE___me_check_47;
  tUInt8 DEF_CAN_FIRE___me_check_47;
  tUInt8 DEF_WILL_FIRE___me_check_46;
  tUInt8 DEF_CAN_FIRE___me_check_46;
  tUInt8 DEF_WILL_FIRE___me_check_45;
  tUInt8 DEF_CAN_FIRE___me_check_45;
  tUInt8 DEF_WILL_FIRE___me_check_44;
  tUInt8 DEF_CAN_FIRE___me_check_44;
  tUInt8 DEF_WILL_FIRE___me_check_43;
  tUInt8 DEF_CAN_FIRE___me_check_43;
  tUInt8 DEF_WILL_FIRE_RL_testFSM_fsm_start;
  tUInt8 DEF_CAN_FIRE_RL_testFSM_fsm_start;
  tUInt8 DEF_WILL_FIRE_RL_testFSM_idle_l68c5;
  tUInt8 DEF_CAN_FIRE_RL_testFSM_idle_l68c5;
  tUInt8 DEF_WILL_FIRE_RL_testFSM_action_l74c9;
  tUInt8 DEF_CAN_FIRE_RL_testFSM_action_l74c9;
  tUInt8 DEF_WILL_FIRE_RL_testFSM_action_l73c16;
  tUInt8 DEF_CAN_FIRE_RL_testFSM_action_l73c16;
  tUInt8 DEF_WILL_FIRE_RL_testFSM_action_l72c9;
  tUInt8 DEF_CAN_FIRE_RL_testFSM_action_l72c9;
  tUInt8 DEF_WILL_FIRE_RL_testFSM_action_l71c16;
  tUInt8 DEF_CAN_FIRE_RL_testFSM_action_l71c16;
  tUInt8 DEF_WILL_FIRE_RL_testFSM_action_l70c9;
  tUInt8 DEF_CAN_FIRE_RL_testFSM_action_l70c9;
  tUInt8 DEF_WILL_FIRE_RL_testFSM_action_l69c18;
  tUInt8 DEF_CAN_FIRE_RL_testFSM_action_l69c18;
  tUInt8 DEF_WILL_FIRE_RL_testFSM_restart;
  tUInt8 DEF_CAN_FIRE_RL_testFSM_restart;
  tUInt8 DEF_WILL_FIRE_RL_testFSM_state_every;
  tUInt8 DEF_CAN_FIRE_RL_testFSM_state_every;
  tUInt8 DEF_WILL_FIRE_RL_testFSM_state_fired__dreg_update;
  tUInt8 DEF_CAN_FIRE_RL_testFSM_state_fired__dreg_update;
  tUInt8 DEF_WILL_FIRE_RL_testFSM_state_handle_abort;
  tUInt8 DEF_CAN_FIRE_RL_testFSM_state_handle_abort;
  tUInt8 DEF_WILL_FIRE_RL_testFSM_start_reg__dreg_update;
  tUInt8 DEF_CAN_FIRE_RL_testFSM_start_reg__dreg_update;
  tUInt8 DEF_WILL_FIRE_RL_counter;
  tUInt8 DEF_CAN_FIRE_RL_counter;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_finish;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_finish;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_start;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_start;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_finish;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_finish;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_32;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_32;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_31;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_31;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_30;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_30;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_29;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_29;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_28;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_28;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_27;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_27;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_26;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_26;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_25;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_25;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_24;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_24;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_23;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_23;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_22;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_22;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_21;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_21;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_20;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_20;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_19;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_19;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_18;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_18;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_17;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_17;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_16;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_16;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_15;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_15;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_14;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_14;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_13;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_13;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_12;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_12;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_11;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_11;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_10;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_10;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_9;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_9;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_8;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_8;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_7;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_7;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_6;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_6;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_5;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_5;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_4;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_4;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_3;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_3;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_2;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_2;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work_1;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work_1;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_work;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_work;
  tUInt8 DEF_WILL_FIRE_RL_sqrtfxm_sqrt_start;
  tUInt8 DEF_CAN_FIRE_RL_sqrtfxm_sqrt_start;
  tUInt8 DEF_CAN_FIRE_get;
  tUInt8 DEF_testFSM_abort_whas__470_AND_testFSM_abort_wget_ETC___d1627;
  tUInt8 DEF_CAN_FIRE_initialize;
  tUInt8 DEF_testFSM_state_mkFSMstate_read____d1497;
  tUInt8 DEF_testFSM_state_fired__h59937;
  tUInt8 DEF_testFSM_abort_whas____d1470;
  tUInt8 DEF_testFSM_abort_wget____d1471;
  tUInt8 DEF_testFSM_start_reg_1__h59935;
  tUInt8 DEF_testFSM_start_reg__h62936;
  tUInt8 DEF_testFSM_state_mkFSMstate_read__497_EQ_6___d1500;
  tUInt8 DEF_testFSM_abort_whas__470_AND_testFSM_abort_wget_ETC___d1501;
  tUInt8 DEF_testFSM_abort_whas__470_AND_testFSM_abort_wget_ETC___d1472;
 
 /* Local definitions */
 private:
  tUInt32 DEF_signed_cycle_465___d1608;
  tUInt32 DEF_b__h48936;
  tUWide DEF_ab__h37444;
  tUWide DEF_ab__h37087;
  tUWide DEF_ab__h36659;
  tUWide DEF_ab__h36231;
  tUWide DEF_ab__h35803;
  tUWide DEF_ab__h35375;
  tUWide DEF_ab__h34947;
  tUWide DEF_ab__h34519;
  tUWide DEF_ab__h34091;
  tUWide DEF_ab__h33663;
  tUWide DEF_ab__h33235;
  tUWide DEF_ab__h32807;
  tUWide DEF_ab__h32379;
  tUWide DEF_ab__h31951;
  tUWide DEF_ab__h31523;
  tUWide DEF_ab__h31095;
  tUWide DEF_ab__h30667;
  tUWide DEF_ab__h30239;
  tUWide DEF_ab__h29811;
  tUWide DEF_ab__h29383;
  tUWide DEF_ab__h28955;
  tUWide DEF_ab__h28527;
  tUWide DEF_ab__h28099;
  tUWide DEF_ab__h27671;
  tUWide DEF_ab__h27243;
  tUWide DEF_ab__h26815;
  tUWide DEF_ab__h26387;
  tUWide DEF_ab__h25959;
  tUWide DEF_ab__h25531;
  tUWide DEF_ab__h25103;
  tUWide DEF_ab__h24675;
  tUWide DEF_ab__h24247;
  tUWide DEF_ab__h23819;
  tUWide DEF_ab__h23383;
  tUWide DEF_ab__h48505;
  tUWide DEF_ab__h62472;
  tUInt64 DEF_x__h60500;
  tUWide DEF_sqrtfxm_sqrt_fNext_31_first__264_BITS_191_TO_0___d1277;
  tUWide DEF_sqrtfxm_sqrt_fNext_30_first__229_BITS_191_TO_0___d1242;
  tUWide DEF_sqrtfxm_sqrt_fNext_29_first__194_BITS_191_TO_0___d1207;
  tUWide DEF_sqrtfxm_sqrt_fNext_28_first__159_BITS_191_TO_0___d1172;
  tUWide DEF_sqrtfxm_sqrt_fNext_27_first__124_BITS_191_TO_0___d1137;
  tUWide DEF_sqrtfxm_sqrt_fNext_26_first__089_BITS_191_TO_0___d1102;
  tUWide DEF_sqrtfxm_sqrt_fNext_25_first__054_BITS_191_TO_0___d1067;
  tUWide DEF_sqrtfxm_sqrt_fNext_24_first__019_BITS_191_TO_0___d1032;
  tUWide DEF_sqrtfxm_sqrt_fNext_23_first__84_BITS_191_TO_0___d997;
  tUWide DEF_sqrtfxm_sqrt_fNext_22_first__49_BITS_191_TO_0___d962;
  tUWide DEF_sqrtfxm_sqrt_fNext_21_first__14_BITS_191_TO_0___d927;
  tUWide DEF_sqrtfxm_sqrt_fNext_20_first__79_BITS_191_TO_0___d892;
  tUWide DEF_sqrtfxm_sqrt_fNext_19_first__44_BITS_191_TO_0___d857;
  tUWide DEF_sqrtfxm_sqrt_fNext_18_first__09_BITS_191_TO_0___d822;
  tUWide DEF_sqrtfxm_sqrt_fNext_17_first__74_BITS_191_TO_0___d787;
  tUWide DEF_sqrtfxm_sqrt_fNext_16_first__39_BITS_191_TO_0___d752;
  tUWide DEF_sqrtfxm_sqrt_fNext_15_first__04_BITS_191_TO_0___d717;
  tUWide DEF_sqrtfxm_sqrt_fNext_14_first__69_BITS_191_TO_0___d682;
  tUWide DEF_sqrtfxm_sqrt_fNext_13_first__34_BITS_191_TO_0___d647;
  tUWide DEF_sqrtfxm_sqrt_fNext_12_first__99_BITS_191_TO_0___d612;
  tUWide DEF_sqrtfxm_sqrt_fNext_11_first__64_BITS_191_TO_0___d577;
  tUWide DEF_sqrtfxm_sqrt_fNext_10_first__29_BITS_191_TO_0___d542;
  tUWide DEF_sqrtfxm_sqrt_fNext_9_first__94_BITS_191_TO_0___d507;
  tUWide DEF_sqrtfxm_sqrt_fNext_8_first__59_BITS_191_TO_0___d472;
  tUWide DEF_sqrtfxm_sqrt_fNext_7_first__24_BITS_191_TO_0___d437;
  tUWide DEF_sqrtfxm_sqrt_fNext_6_first__89_BITS_191_TO_0___d402;
  tUWide DEF_sqrtfxm_sqrt_fNext_5_first__54_BITS_191_TO_0___d367;
  tUWide DEF_sqrtfxm_sqrt_fNext_4_first__19_BITS_191_TO_0___d332;
  tUWide DEF_sqrtfxm_sqrt_fNext_3_first__84_BITS_191_TO_0___d297;
  tUWide DEF_sqrtfxm_sqrt_fNext_2_first__49_BITS_191_TO_0___d262;
  tUWide DEF_sqrtfxm_sqrt_fNext_1_first__14_BITS_191_TO_0___d227;
  tUWide DEF_sqrtfxm_sqrt_fNext_0_first__79_BITS_191_TO_0___d192;
  tUWide DEF_sqrtfxm_sqrt_fFirst_first__44_BITS_191_TO_0___d157;
  tUWide DEF_sqrtfxm_sqrt_fNext_31_first__264_BITS_127_TO_0___d1284;
  tUWide DEF_sqrtfxm_sqrt_fNext_30_first__229_BITS_127_TO_0___d1249;
  tUWide DEF_sqrtfxm_sqrt_fNext_29_first__194_BITS_127_TO_0___d1214;
  tUWide DEF_sqrtfxm_sqrt_fNext_28_first__159_BITS_127_TO_0___d1179;
  tUWide DEF_sqrtfxm_sqrt_fNext_27_first__124_BITS_127_TO_0___d1144;
  tUWide DEF_sqrtfxm_sqrt_fNext_26_first__089_BITS_127_TO_0___d1109;
  tUWide DEF_sqrtfxm_sqrt_fNext_25_first__054_BITS_127_TO_0___d1074;
  tUWide DEF_sqrtfxm_sqrt_fNext_24_first__019_BITS_127_TO_0___d1039;
  tUWide DEF_sqrtfxm_sqrt_fNext_23_first__84_BITS_127_TO_0___d1004;
  tUWide DEF_sqrtfxm_sqrt_fNext_22_first__49_BITS_127_TO_0___d969;
  tUWide DEF_sqrtfxm_sqrt_fNext_21_first__14_BITS_127_TO_0___d934;
  tUWide DEF_sqrtfxm_sqrt_fNext_20_first__79_BITS_127_TO_0___d899;
  tUWide DEF_sqrtfxm_sqrt_fNext_19_first__44_BITS_127_TO_0___d864;
  tUWide DEF_sqrtfxm_sqrt_fNext_18_first__09_BITS_127_TO_0___d829;
  tUWide DEF_sqrtfxm_sqrt_fNext_17_first__74_BITS_127_TO_0___d794;
  tUWide DEF_sqrtfxm_sqrt_fNext_16_first__39_BITS_127_TO_0___d759;
  tUWide DEF_sqrtfxm_sqrt_fNext_15_first__04_BITS_127_TO_0___d724;
  tUWide DEF_sqrtfxm_sqrt_fNext_14_first__69_BITS_127_TO_0___d689;
  tUWide DEF_sqrtfxm_sqrt_fNext_13_first__34_BITS_127_TO_0___d654;
  tUWide DEF_sqrtfxm_sqrt_fNext_12_first__99_BITS_127_TO_0___d619;
  tUWide DEF_sqrtfxm_sqrt_fNext_11_first__64_BITS_127_TO_0___d584;
  tUWide DEF_sqrtfxm_sqrt_fNext_10_first__29_BITS_127_TO_0___d549;
  tUWide DEF_sqrtfxm_sqrt_fNext_9_first__94_BITS_127_TO_0___d514;
  tUWide DEF_sqrtfxm_sqrt_fNext_8_first__59_BITS_127_TO_0___d479;
  tUWide DEF_sqrtfxm_sqrt_fNext_7_first__24_BITS_127_TO_0___d444;
  tUWide DEF_sqrtfxm_sqrt_fNext_6_first__89_BITS_127_TO_0___d409;
  tUWide DEF_sqrtfxm_sqrt_fNext_5_first__54_BITS_127_TO_0___d374;
  tUWide DEF_sqrtfxm_sqrt_fNext_4_first__19_BITS_127_TO_0___d339;
  tUWide DEF_sqrtfxm_sqrt_fNext_3_first__84_BITS_127_TO_0___d304;
  tUWide DEF_sqrtfxm_sqrt_fNext_2_first__49_BITS_127_TO_0___d269;
  tUWide DEF_sqrtfxm_sqrt_fNext_1_first__14_BITS_127_TO_0___d234;
  tUWide DEF_sqrtfxm_sqrt_fNext_0_first__79_BITS_127_TO_0___d199;
  tUWide DEF_sqrtfxm_sqrt_fFirst_first__44_BITS_127_TO_0___d164;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d1602;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d1601;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d1593;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d1592;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d1584;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d1583;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_0_CO_ETC___d1575;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_0_CO_ETC___d1574;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0__ETC___d1566;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0__ETC___d1565;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d1557;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d1556;
  tUWide DEF__10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d1548;
  tUWide DEF__10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d1547;
  tUWide DEF__10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_valsqr_ETC___d1539;
  tUWide DEF__10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_valsqr_ETC___d1538;
  tUWide DEF__10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_valsqrIn_503__ETC___d1530;
  tUWide DEF__10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_valsqrIn_503__ETC___d1529;
  tUWide DEF__0_CONCAT_IF_SEXT_valsqrIn_503_BITS_63_TO_32_50_ETC___d1597;
  tUWide DEF__0_CONCAT_IF_SEXT_valsqrIn_503_BITS_63_TO_32_50_ETC___d1588;
  tUWide DEF__0_CONCAT_IF_SEXT_valsqrIn_503_BITS_63_TO_32_50_ETC___d1579;
  tUWide DEF__0_CONCAT_IF_SEXT_valsqrIn_503_BITS_63_TO_32_50_ETC___d1570;
  tUWide DEF__0_CONCAT_IF_SEXT_valsqrIn_503_BITS_63_TO_32_50_ETC___d1561;
  tUWide DEF__0_CONCAT_IF_SEXT_valsqrIn_503_BITS_63_TO_32_50_ETC___d1552;
  tUWide DEF__0_CONCAT_IF_SEXT_valsqrIn_503_BITS_63_TO_32_50_ETC___d1543;
  tUWide DEF__0_CONCAT_IF_SEXT_valsqrIn_503_BITS_63_TO_32_50_ETC___d1534;
  tUWide DEF__0_CONCAT_IF_SEXT_valsqrIn_503_BITS_63_TO_32_50_ETC___d1526;
  tUWide DEF__0_CONCAT_IF_SEXT_valsqrIn_503_BITS_63_TO_32_50_ETC___d1523;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_valsqrIn_503_BITS_63_ETC___d1603;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_valsqrIn_503_BITS_63_ETC___d1594;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_valsqrIn_503_BITS_63_ETC___d1585;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_valsqrIn_503_BITS_63_ETC___d1576;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_valsqrIn_503_BITS_63_ETC___d1567;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_valsqrIn_503_BITS_63_ETC___d1558;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_valsqrIn_503_BITS_63_ETC___d1549;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_valsqrIn_503_BITS_63_ETC___d1540;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_valsqrIn_503_BITS_63_ETC___d1531;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_31_first__264_BIT_256_26_ETC___d1294;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_31_first__264_BITS_63_TO_ETC___d1293;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_30_first__229_BIT_256_23_ETC___d1259;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_30_first__229_BITS_63_TO_ETC___d1258;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_29_first__194_BIT_256_19_ETC___d1224;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_29_first__194_BITS_63_TO_ETC___d1223;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_28_first__159_BIT_256_16_ETC___d1189;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_28_first__159_BITS_63_TO_ETC___d1188;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_27_first__124_BIT_256_12_ETC___d1154;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_27_first__124_BITS_63_TO_ETC___d1153;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_26_first__089_BIT_256_09_ETC___d1119;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_26_first__089_BITS_63_TO_ETC___d1118;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_25_first__054_BIT_256_05_ETC___d1084;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_25_first__054_BITS_63_TO_ETC___d1083;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_24_first__019_BIT_256_02_ETC___d1049;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_24_first__019_BITS_63_TO_ETC___d1048;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_23_first__84_BIT_256_85__ETC___d1014;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_23_first__84_BITS_63_TO__ETC___d1013;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_22_first__49_BIT_256_50__ETC___d979;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_22_first__49_BITS_63_TO__ETC___d978;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_21_first__14_BIT_256_15__ETC___d944;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_21_first__14_BITS_63_TO__ETC___d943;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_20_first__79_BIT_256_80__ETC___d909;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_20_first__79_BITS_63_TO__ETC___d908;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_19_first__44_BIT_256_45__ETC___d874;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_19_first__44_BITS_63_TO__ETC___d873;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_18_first__09_BIT_256_10__ETC___d839;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_18_first__09_BITS_63_TO__ETC___d838;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_17_first__74_BIT_256_75__ETC___d804;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_17_first__74_BITS_63_TO__ETC___d803;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_16_first__39_BIT_256_40__ETC___d769;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_16_first__39_BITS_63_TO__ETC___d768;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_15_first__04_BIT_256_05__ETC___d734;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_15_first__04_BITS_63_TO__ETC___d733;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_14_first__69_BIT_256_70__ETC___d699;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_14_first__69_BITS_63_TO__ETC___d698;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_13_first__34_BIT_256_35__ETC___d664;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_13_first__34_BITS_63_TO__ETC___d663;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_12_first__99_BIT_256_00__ETC___d629;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_12_first__99_BITS_63_TO__ETC___d628;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_11_first__64_BIT_256_65__ETC___d594;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_11_first__64_BITS_63_TO__ETC___d593;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_10_first__29_BIT_256_30__ETC___d559;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_10_first__29_BITS_63_TO__ETC___d558;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_9_first__94_BIT_256_95_T_ETC___d524;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_9_first__94_BITS_63_TO_0_ETC___d523;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_8_first__59_BIT_256_60_T_ETC___d489;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_8_first__59_BITS_63_TO_0_ETC___d488;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_7_first__24_BIT_256_25_T_ETC___d454;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_7_first__24_BITS_63_TO_0_ETC___d453;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_6_first__89_BIT_256_90_T_ETC___d419;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_6_first__89_BITS_63_TO_0_ETC___d418;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_5_first__54_BIT_256_55_T_ETC___d384;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_5_first__54_BITS_63_TO_0_ETC___d383;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_4_first__19_BIT_256_20_T_ETC___d349;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_4_first__19_BITS_63_TO_0_ETC___d348;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_3_first__84_BIT_256_85_T_ETC___d314;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_3_first__84_BITS_63_TO_0_ETC___d313;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_2_first__49_BIT_256_50_T_ETC___d279;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_2_first__49_BITS_63_TO_0_ETC___d278;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_1_first__14_BIT_256_15_T_ETC___d244;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_1_first__14_BITS_63_TO_0_ETC___d243;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_0_first__79_BIT_256_80_T_ETC___d209;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_0_first__79_BITS_63_TO_0_ETC___d208;
  tUWide DEF_IF_sqrtfxm_sqrt_fFirst_first__44_BIT_256_45_TH_ETC___d174;
  tUWide DEF_IF_sqrtfxm_sqrt_fFirst_first__44_BITS_63_TO_0__ETC___d173;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_31_first__264_BITS_63_TO_ETC___d1292;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_31_first__264_BITS_191_T_ETC___d1291;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_30_first__229_BITS_63_TO_ETC___d1257;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_30_first__229_BITS_191_T_ETC___d1256;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_29_first__194_BITS_63_TO_ETC___d1222;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_29_first__194_BITS_191_T_ETC___d1221;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_28_first__159_BITS_63_TO_ETC___d1187;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_28_first__159_BITS_191_T_ETC___d1186;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_27_first__124_BITS_63_TO_ETC___d1152;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_27_first__124_BITS_191_T_ETC___d1151;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_26_first__089_BITS_63_TO_ETC___d1117;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_26_first__089_BITS_191_T_ETC___d1116;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_25_first__054_BITS_63_TO_ETC___d1082;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_25_first__054_BITS_191_T_ETC___d1081;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_24_first__019_BITS_63_TO_ETC___d1047;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_24_first__019_BITS_191_T_ETC___d1046;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_23_first__84_BITS_63_TO__ETC___d1012;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_23_first__84_BITS_191_TO_ETC___d1011;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_22_first__49_BITS_63_TO__ETC___d977;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_22_first__49_BITS_191_TO_ETC___d976;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_21_first__14_BITS_63_TO__ETC___d942;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_21_first__14_BITS_191_TO_ETC___d941;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_20_first__79_BITS_63_TO__ETC___d907;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_20_first__79_BITS_191_TO_ETC___d906;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_19_first__44_BITS_63_TO__ETC___d872;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_19_first__44_BITS_191_TO_ETC___d871;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_18_first__09_BITS_63_TO__ETC___d837;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_18_first__09_BITS_191_TO_ETC___d836;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_17_first__74_BITS_63_TO__ETC___d802;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_17_first__74_BITS_191_TO_ETC___d801;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_16_first__39_BITS_63_TO__ETC___d767;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_16_first__39_BITS_191_TO_ETC___d766;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_15_first__04_BITS_63_TO__ETC___d732;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_15_first__04_BITS_191_TO_ETC___d731;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_14_first__69_BITS_63_TO__ETC___d697;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_14_first__69_BITS_191_TO_ETC___d696;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_13_first__34_BITS_63_TO__ETC___d662;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_13_first__34_BITS_191_TO_ETC___d661;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_12_first__99_BITS_63_TO__ETC___d627;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_12_first__99_BITS_191_TO_ETC___d626;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_11_first__64_BITS_63_TO__ETC___d592;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_11_first__64_BITS_191_TO_ETC___d591;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_10_first__29_BITS_63_TO__ETC___d557;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_10_first__29_BITS_191_TO_ETC___d556;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_9_first__94_BITS_63_TO_0_ETC___d522;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_9_first__94_BITS_191_TO__ETC___d521;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_8_first__59_BITS_63_TO_0_ETC___d487;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_8_first__59_BITS_191_TO__ETC___d486;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_7_first__24_BITS_63_TO_0_ETC___d452;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_7_first__24_BITS_191_TO__ETC___d451;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_6_first__89_BITS_63_TO_0_ETC___d417;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_6_first__89_BITS_191_TO__ETC___d416;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_5_first__54_BITS_63_TO_0_ETC___d382;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_5_first__54_BITS_191_TO__ETC___d381;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_4_first__19_BITS_63_TO_0_ETC___d347;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_4_first__19_BITS_191_TO__ETC___d346;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_3_first__84_BITS_63_TO_0_ETC___d312;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_3_first__84_BITS_191_TO__ETC___d311;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_2_first__49_BITS_63_TO_0_ETC___d277;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_2_first__49_BITS_191_TO__ETC___d276;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_1_first__14_BITS_63_TO_0_ETC___d242;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_1_first__14_BITS_191_TO__ETC___d241;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_0_first__79_BITS_63_TO_0_ETC___d207;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_0_first__79_BITS_191_TO__ETC___d206;
  tUWide DEF_IF_sqrtfxm_sqrt_fFirst_first__44_BITS_63_TO_0__ETC___d172;
  tUWide DEF_IF_sqrtfxm_sqrt_fFirst_first__44_BITS_191_TO_1_ETC___d171;
  tUWide DEF_y__h61539;
  tUWide DEF_y__h61448;
  tUWide DEF_y__h61357;
  tUWide DEF_y__h61266;
  tUWide DEF_y__h61175;
  tUWide DEF_y__h61084;
  tUWide DEF_y__h60993;
  tUWide DEF_y__h60902;
  tUWide DEF_digit__h60683;
  tUWide DEF__0_CONCAT_IF_SEXT_valsqrIn_503_BITS_63_TO_32_50_ETC___d1522;
  tUWide DEF_tx__h61478;
  tUWide DEF_tx__h61387;
  tUWide DEF_tx__h61296;
  tUWide DEF_tx__h61205;
  tUWide DEF_tx__h61114;
  tUWide DEF_tx__h61023;
  tUWide DEF_tx__h60932;
  tUWide DEF_tx__h60841;
  tUWide DEF_tx__h60750;
  tUWide DEF_digit__h61389;
  tUWide DEF_digit__h61298;
  tUWide DEF_digit__h61207;
  tUWide DEF_digit__h61116;
  tUWide DEF_digit__h61025;
  tUWide DEF_digit__h60934;
  tUWide DEF_digit__h60843;
  tUWide DEF_digit__h60752;
  tUWide DEF__0_CONCAT_DONTCARE_CONCAT_sqrtfxm_sqrt_fRequest_ETC___d140;
  tUWide DEF__0_CONCAT_IF_sqrtfxm_sqrt_fRequest_first_BIT_63_ETC___d139;
  tUWide DEF_sqrtfxm_sqrt_fNext_31_first__264_BIT_256_265_O_ETC___d1295;
  tUWide DEF_sqrtfxm_sqrt_fNext_30_first__229_BIT_256_230_O_ETC___d1260;
  tUWide DEF_sqrtfxm_sqrt_fNext_29_first__194_BIT_256_195_O_ETC___d1225;
  tUWide DEF_sqrtfxm_sqrt_fNext_28_first__159_BIT_256_160_O_ETC___d1190;
  tUWide DEF_sqrtfxm_sqrt_fNext_27_first__124_BIT_256_125_O_ETC___d1155;
  tUWide DEF_sqrtfxm_sqrt_fNext_26_first__089_BIT_256_090_O_ETC___d1120;
  tUWide DEF_sqrtfxm_sqrt_fNext_25_first__054_BIT_256_055_O_ETC___d1085;
  tUWide DEF_sqrtfxm_sqrt_fNext_24_first__019_BIT_256_020_O_ETC___d1050;
  tUWide DEF_sqrtfxm_sqrt_fNext_23_first__84_BIT_256_85_OR__ETC___d1015;
  tUWide DEF_sqrtfxm_sqrt_fNext_22_first__49_BIT_256_50_OR__ETC___d980;
  tUWide DEF_sqrtfxm_sqrt_fNext_21_first__14_BIT_256_15_OR__ETC___d945;
  tUWide DEF_sqrtfxm_sqrt_fNext_20_first__79_BIT_256_80_OR__ETC___d910;
  tUWide DEF_sqrtfxm_sqrt_fNext_19_first__44_BIT_256_45_OR__ETC___d875;
  tUWide DEF_sqrtfxm_sqrt_fNext_18_first__09_BIT_256_10_OR__ETC___d840;
  tUWide DEF_sqrtfxm_sqrt_fNext_17_first__74_BIT_256_75_OR__ETC___d805;
  tUWide DEF_sqrtfxm_sqrt_fNext_16_first__39_BIT_256_40_OR__ETC___d770;
  tUWide DEF_sqrtfxm_sqrt_fNext_15_first__04_BIT_256_05_OR__ETC___d735;
  tUWide DEF_sqrtfxm_sqrt_fNext_14_first__69_BIT_256_70_OR__ETC___d700;
  tUWide DEF_sqrtfxm_sqrt_fNext_13_first__34_BIT_256_35_OR__ETC___d665;
  tUWide DEF_sqrtfxm_sqrt_fNext_12_first__99_BIT_256_00_OR__ETC___d630;
  tUWide DEF_sqrtfxm_sqrt_fNext_11_first__64_BIT_256_65_OR__ETC___d595;
  tUWide DEF_sqrtfxm_sqrt_fNext_10_first__29_BIT_256_30_OR__ETC___d560;
  tUWide DEF_sqrtfxm_sqrt_fNext_9_first__94_BIT_256_95_OR_s_ETC___d525;
  tUWide DEF_sqrtfxm_sqrt_fNext_8_first__59_BIT_256_60_OR_s_ETC___d490;
  tUWide DEF_sqrtfxm_sqrt_fNext_7_first__24_BIT_256_25_OR_s_ETC___d455;
  tUWide DEF_sqrtfxm_sqrt_fNext_6_first__89_BIT_256_90_OR_s_ETC___d420;
  tUWide DEF_sqrtfxm_sqrt_fNext_5_first__54_BIT_256_55_OR_s_ETC___d385;
  tUWide DEF_sqrtfxm_sqrt_fNext_4_first__19_BIT_256_20_OR_s_ETC___d350;
  tUWide DEF_sqrtfxm_sqrt_fNext_3_first__84_BIT_256_85_OR_s_ETC___d315;
  tUWide DEF_sqrtfxm_sqrt_fNext_2_first__49_BIT_256_50_OR_s_ETC___d280;
  tUWide DEF_sqrtfxm_sqrt_fNext_1_first__14_BIT_256_15_OR_s_ETC___d245;
  tUWide DEF_sqrtfxm_sqrt_fFirst_first__44_BIT_256_45_OR_sq_ETC___d175;
  tUWide DEF_sqrtfxm_sqrt_fNext_0_first__79_BIT_256_80_OR_s_ETC___d210;
  tUWide DEF_digit__h61480;
  tUWide DEF_IF_sqrtfxm_sqrt_fNext_32_first__299_BIT_256_30_ETC___d1306;
  tUWide DEF_IF_sqrtfxm_fShift_first__453_BIT_6_454_THEN_sq_ETC___d1464;
 
 /* Rules */
 public:
  void RL_sqrtfxm_sqrt_start();
  void RL_sqrtfxm_sqrt_work();
  void RL_sqrtfxm_sqrt_work_1();
  void RL_sqrtfxm_sqrt_work_2();
  void RL_sqrtfxm_sqrt_work_3();
  void RL_sqrtfxm_sqrt_work_4();
  void RL_sqrtfxm_sqrt_work_5();
  void RL_sqrtfxm_sqrt_work_6();
  void RL_sqrtfxm_sqrt_work_7();
  void RL_sqrtfxm_sqrt_work_8();
  void RL_sqrtfxm_sqrt_work_9();
  void RL_sqrtfxm_sqrt_work_10();
  void RL_sqrtfxm_sqrt_work_11();
  void RL_sqrtfxm_sqrt_work_12();
  void RL_sqrtfxm_sqrt_work_13();
  void RL_sqrtfxm_sqrt_work_14();
  void RL_sqrtfxm_sqrt_work_15();
  void RL_sqrtfxm_sqrt_work_16();
  void RL_sqrtfxm_sqrt_work_17();
  void RL_sqrtfxm_sqrt_work_18();
  void RL_sqrtfxm_sqrt_work_19();
  void RL_sqrtfxm_sqrt_work_20();
  void RL_sqrtfxm_sqrt_work_21();
  void RL_sqrtfxm_sqrt_work_22();
  void RL_sqrtfxm_sqrt_work_23();
  void RL_sqrtfxm_sqrt_work_24();
  void RL_sqrtfxm_sqrt_work_25();
  void RL_sqrtfxm_sqrt_work_26();
  void RL_sqrtfxm_sqrt_work_27();
  void RL_sqrtfxm_sqrt_work_28();
  void RL_sqrtfxm_sqrt_work_29();
  void RL_sqrtfxm_sqrt_work_30();
  void RL_sqrtfxm_sqrt_work_31();
  void RL_sqrtfxm_sqrt_work_32();
  void RL_sqrtfxm_sqrt_finish();
  void RL_sqrtfxm_start();
  void RL_sqrtfxm_finish();
  void RL_counter();
  void RL_testFSM_start_reg__dreg_update();
  void RL_testFSM_state_handle_abort();
  void RL_testFSM_state_fired__dreg_update();
  void RL_testFSM_state_every();
  void RL_testFSM_restart();
  void RL_testFSM_action_l69c18();
  void RL_testFSM_action_l70c9();
  void RL_testFSM_action_l71c16();
  void RL_testFSM_action_l72c9();
  void RL_testFSM_action_l73c16();
  void RL_testFSM_action_l74c9();
  void RL_testFSM_idle_l68c5();
  void RL_testFSM_fsm_start();
  void __me_check_43();
  void __me_check_44();
  void __me_check_45();
  void __me_check_46();
  void __me_check_47();
 
 /* Methods */
 public:
  void METH_initialize(tUInt32 ARG_initialize_s1, tUInt32 ARG_initialize_s2);
  tUInt8 METH_RDY_initialize();
  tUWide METH_get(tUInt64 ARG_get_val);
  tUInt8 METH_RDY_get();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkBoxMuller &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkBoxMuller &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkBoxMuller &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkBoxMuller &backing);
};

#endif /* ifndef __mkBoxMuller_h__ */
