/*
 * Generated by Bluespec Compiler, version 2014.07.A (build 34078, 2014-07-30)
 * 
 * On Sun May  6 18:56:31 -03 2018
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkBoxMullerTb_h__
#define __mkBoxMullerTb_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkBoxMuller.h"
#include "mkLogTableFxdP.h"


/* Class declaration for the mkBoxMullerTb module */
class MOD_mkBoxMullerTb : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt64> INST__unnamed_;
  MOD_Wire<tUInt8> INST_abort;
  MOD_mkBoxMuller INST_boxmuller;
  MOD_Reg<tUInt32> INST_cont;
  MOD_Reg<tUInt64> INST_i;
  MOD_mkLogTableFxdP INST_mLUT;
  MOD_Reg<tUInt32> INST_n;
  MOD_Reg<tUInt8> INST_running;
  MOD_Reg<tUInt8> INST_start_reg;
  MOD_Reg<tUInt8> INST_start_reg_1;
  MOD_Wire<tUInt8> INST_start_reg_2;
  MOD_Wire<tUInt8> INST_start_wire;
  MOD_Reg<tUInt8> INST_state_can_overlap;
  MOD_Reg<tUInt8> INST_state_fired;
  MOD_Wire<tUInt8> INST_state_fired_1;
  MOD_ConfigReg<tUInt8> INST_state_mkFSMstate;
  MOD_Wire<tUInt8> INST_state_overlap_pw;
  MOD_Wire<tUInt8> INST_state_set_pw;
  MOD_Reg<tUWide> INST_tup;
  MOD_Reg<tUWide> INST_uniform_rand_num;
 
 /* Constructor */
 public:
  MOD_mkBoxMullerTb(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE___me_check_16;
  tUInt8 DEF_CAN_FIRE___me_check_16;
  tUInt8 DEF_WILL_FIRE___me_check_15;
  tUInt8 DEF_CAN_FIRE___me_check_15;
  tUInt8 DEF_WILL_FIRE___me_check_14;
  tUInt8 DEF_CAN_FIRE___me_check_14;
  tUInt8 DEF_WILL_FIRE___me_check_13;
  tUInt8 DEF_CAN_FIRE___me_check_13;
  tUInt8 DEF_WILL_FIRE___me_check_12;
  tUInt8 DEF_CAN_FIRE___me_check_12;
  tUInt8 DEF_WILL_FIRE___me_check_11;
  tUInt8 DEF_CAN_FIRE___me_check_11;
  tUInt8 DEF_WILL_FIRE___me_check_10;
  tUInt8 DEF_CAN_FIRE___me_check_10;
  tUInt8 DEF_WILL_FIRE___me_check_9;
  tUInt8 DEF_CAN_FIRE___me_check_9;
  tUInt8 DEF_WILL_FIRE___me_check_8;
  tUInt8 DEF_CAN_FIRE___me_check_8;
  tUInt8 DEF_WILL_FIRE___me_check_7;
  tUInt8 DEF_CAN_FIRE___me_check_7;
  tUInt8 DEF_WILL_FIRE___me_check_6;
  tUInt8 DEF_CAN_FIRE___me_check_6;
  tUInt8 DEF_WILL_FIRE___me_check_5;
  tUInt8 DEF_CAN_FIRE___me_check_5;
  tUInt8 DEF_WILL_FIRE_RL_auto_finish;
  tUInt8 DEF_CAN_FIRE_RL_auto_finish;
  tUInt8 DEF_WILL_FIRE_RL_auto_start;
  tUInt8 DEF_CAN_FIRE_RL_auto_start;
  tUInt8 DEF_WILL_FIRE_RL_fsm_start;
  tUInt8 DEF_CAN_FIRE_RL_fsm_start;
  tUInt8 DEF_WILL_FIRE_RL_idle_l69c9_1;
  tUInt8 DEF_CAN_FIRE_RL_idle_l69c9_1;
  tUInt8 DEF_WILL_FIRE_RL_idle_l69c9;
  tUInt8 DEF_CAN_FIRE_RL_idle_l69c9;
  tUInt8 DEF_WILL_FIRE_RL_action_l107c13;
  tUInt8 DEF_CAN_FIRE_RL_action_l107c13;
  tUInt8 DEF_WILL_FIRE_RL_action_l99c13;
  tUInt8 DEF_CAN_FIRE_RL_action_l99c13;
  tUInt8 DEF_WILL_FIRE_RL_action_l98c13;
  tUInt8 DEF_CAN_FIRE_RL_action_l98c13;
  tUInt8 DEF_WILL_FIRE_RL_action_l97c22;
  tUInt8 DEF_CAN_FIRE_RL_action_l97c22;
  tUInt8 DEF_WILL_FIRE_RL_action_l96c13;
  tUInt8 DEF_CAN_FIRE_RL_action_l96c13;
  tUInt8 DEF_WILL_FIRE_RL_action_l95c13;
  tUInt8 DEF_CAN_FIRE_RL_action_l95c13;
  tUInt8 DEF_WILL_FIRE_RL_action_l91c13;
  tUInt8 DEF_CAN_FIRE_RL_action_l91c13;
  tUInt8 DEF_WILL_FIRE_RL_action_l89c22;
  tUInt8 DEF_CAN_FIRE_RL_action_l89c22;
  tUInt8 DEF_WILL_FIRE_RL_action_l88c22;
  tUInt8 DEF_CAN_FIRE_RL_action_l88c22;
  tUInt8 DEF_WILL_FIRE_RL_action_l83c12;
  tUInt8 DEF_CAN_FIRE_RL_action_l83c12;
  tUInt8 DEF_WILL_FIRE_RL_action_l79c9;
  tUInt8 DEF_CAN_FIRE_RL_action_l79c9;
  tUInt8 DEF_WILL_FIRE_RL_action_l75c9;
  tUInt8 DEF_CAN_FIRE_RL_action_l75c9;
  tUInt8 DEF_WILL_FIRE_RL_action_l71c9;
  tUInt8 DEF_CAN_FIRE_RL_action_l71c9;
  tUInt8 DEF_WILL_FIRE_RL_restart;
  tUInt8 DEF_CAN_FIRE_RL_restart;
  tUInt8 DEF_WILL_FIRE_RL_state_every;
  tUInt8 DEF_CAN_FIRE_RL_state_every;
  tUInt8 DEF_WILL_FIRE_RL_state_fired__dreg_update;
  tUInt8 DEF_CAN_FIRE_RL_state_fired__dreg_update;
  tUInt8 DEF_WILL_FIRE_RL_state_handle_abort;
  tUInt8 DEF_CAN_FIRE_RL_state_handle_abort;
  tUInt8 DEF_WILL_FIRE_RL_start_reg__dreg_update;
  tUInt8 DEF_CAN_FIRE_RL_start_reg__dreg_update;
  tUInt64 DEF_b__h10296;
 
 /* Local definitions */
 private:
  tUInt64 DEF_v__h35391;
  tUInt64 DEF_v__h35083;
  tUWide DEF_ab__h34741;
  tUWide DEF_ab__h35409;
  tUWide DEF_x__h43966;
  tUWide DEF_x__h45131;
  tUInt32 DEF_in2_i__h29122;
  tUWide DEF_IF_cont_8_BIT_31_9_THEN_NEG_cont_8_CONCAT_0_0__ETC___d66;
  tUWide DEF_IF_cont_8_BIT_31_9_THEN_NEG_cont_8_CONCAT_0_0__ETC___d63;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d427;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d426;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d418;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d417;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d409;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d408;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_0_CO_ETC___d400;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_0_CO_ETC___d399;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0__ETC___d391;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0__ETC___d390;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d382;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d381;
  tUWide DEF__10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d373;
  tUWide DEF__10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d372;
  tUWide DEF__10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_mLUT_g_ETC___d364;
  tUWide DEF__10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_mLUT_g_ETC___d363;
  tUWide DEF__10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_mLUT_get_unif_ETC___d355;
  tUWide DEF__10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_mLUT_get_unif_ETC___d354;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d324;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d323;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d315;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d314;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d306;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d305;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_0_CO_ETC___d297;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_0_CO_ETC___d296;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0__ETC___d288;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0__ETC___d287;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d279;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d278;
  tUWide DEF__10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d270;
  tUWide DEF__10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d269;
  tUWide DEF__10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_unifor_ETC___d261;
  tUWide DEF__10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_unifor_ETC___d260;
  tUWide DEF__10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_uniform_rand__ETC___d252;
  tUWide DEF__10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_uniform_rand__ETC___d251;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d216;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d215;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d207;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d206;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d198;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_M_ETC___d197;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_0_CO_ETC___d189;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_0_CO_ETC___d188;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0__ETC___d180;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0__ETC___d179;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d171;
  tUWide DEF__10_MUL_10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT__ETC___d170;
  tUWide DEF__10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d162;
  tUWide DEF__10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d161;
  tUWide DEF__10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_tup_12_ETC___d153;
  tUWide DEF__10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_tup_12_ETC___d152;
  tUWide DEF__10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_tup_12_BITS_6_ETC___d144;
  tUWide DEF__10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_tup_12_BITS_6_ETC___d143;
  tUWide DEF_IF_NOT_IF_cont_8_BIT_31_9_THEN_NEG_cont_8_CONC_ETC___d78;
  tUWide DEF__0_CONCAT_IF_SEXT_mLUT_get_uniform_rand_num_25__ETC___d422;
  tUWide DEF__0_CONCAT_IF_SEXT_mLUT_get_uniform_rand_num_25__ETC___d413;
  tUWide DEF__0_CONCAT_IF_SEXT_mLUT_get_uniform_rand_num_25__ETC___d404;
  tUWide DEF__0_CONCAT_IF_SEXT_mLUT_get_uniform_rand_num_25__ETC___d395;
  tUWide DEF__0_CONCAT_IF_SEXT_mLUT_get_uniform_rand_num_25__ETC___d386;
  tUWide DEF__0_CONCAT_IF_SEXT_mLUT_get_uniform_rand_num_25__ETC___d377;
  tUWide DEF__0_CONCAT_IF_SEXT_mLUT_get_uniform_rand_num_25__ETC___d368;
  tUWide DEF__0_CONCAT_IF_SEXT_mLUT_get_uniform_rand_num_25__ETC___d359;
  tUWide DEF__0_CONCAT_IF_SEXT_mLUT_get_uniform_rand_num_25__ETC___d351;
  tUWide DEF__0_CONCAT_IF_SEXT_uniform_rand_num_25_BITS_64_T_ETC___d319;
  tUWide DEF__0_CONCAT_IF_SEXT_uniform_rand_num_25_BITS_64_T_ETC___d310;
  tUWide DEF__0_CONCAT_IF_SEXT_uniform_rand_num_25_BITS_64_T_ETC___d301;
  tUWide DEF__0_CONCAT_IF_SEXT_uniform_rand_num_25_BITS_64_T_ETC___d292;
  tUWide DEF__0_CONCAT_IF_SEXT_uniform_rand_num_25_BITS_64_T_ETC___d283;
  tUWide DEF__0_CONCAT_IF_SEXT_uniform_rand_num_25_BITS_64_T_ETC___d274;
  tUWide DEF__0_CONCAT_IF_SEXT_uniform_rand_num_25_BITS_64_T_ETC___d265;
  tUWide DEF__0_CONCAT_IF_SEXT_uniform_rand_num_25_BITS_64_T_ETC___d256;
  tUWide DEF__0_CONCAT_IF_SEXT_uniform_rand_num_25_BITS_64_T_ETC___d248;
  tUWide DEF__0_CONCAT_IF_SEXT_tup_12_BITS_63_TO_32_18_19_BI_ETC___d211;
  tUWide DEF__0_CONCAT_IF_SEXT_tup_12_BITS_63_TO_32_18_19_BI_ETC___d202;
  tUWide DEF__0_CONCAT_IF_SEXT_tup_12_BITS_63_TO_32_18_19_BI_ETC___d193;
  tUWide DEF__0_CONCAT_IF_SEXT_tup_12_BITS_63_TO_32_18_19_BI_ETC___d184;
  tUWide DEF__0_CONCAT_IF_SEXT_tup_12_BITS_63_TO_32_18_19_BI_ETC___d175;
  tUWide DEF__0_CONCAT_IF_SEXT_tup_12_BITS_63_TO_32_18_19_BI_ETC___d166;
  tUWide DEF__0_CONCAT_IF_SEXT_tup_12_BITS_63_TO_32_18_19_BI_ETC___d157;
  tUWide DEF__0_CONCAT_IF_SEXT_tup_12_BITS_63_TO_32_18_19_BI_ETC___d148;
  tUWide DEF__0_CONCAT_IF_SEXT_tup_12_BITS_63_TO_32_18_19_BI_ETC___d140;
  tUInt32 DEF_res_f__h43825;
  tUWide DEF__0_CONCAT_IF_SEXT_mLUT_get_uniform_rand_num_25__ETC___d348;
  tUWide DEF__0_CONCAT_IF_SEXT_uniform_rand_num_25_BITS_64_T_ETC___d245;
  tUWide DEF__0_CONCAT_IF_SEXT_tup_12_BITS_63_TO_32_18_19_BI_ETC___d137;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_mLUT_get_uniform_ran_ETC___d428;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_mLUT_get_uniform_ran_ETC___d419;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_mLUT_get_uniform_ran_ETC___d410;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_mLUT_get_uniform_ran_ETC___d401;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_mLUT_get_uniform_ran_ETC___d392;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_mLUT_get_uniform_ran_ETC___d383;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_mLUT_get_uniform_ran_ETC___d374;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_mLUT_get_uniform_ran_ETC___d365;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_mLUT_get_uniform_ran_ETC___d356;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_uniform_rand_num_25__ETC___d325;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_uniform_rand_num_25__ETC___d316;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_uniform_rand_num_25__ETC___d307;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_uniform_rand_num_25__ETC___d298;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_uniform_rand_num_25__ETC___d289;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_uniform_rand_num_25__ETC___d280;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_uniform_rand_num_25__ETC___d271;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_uniform_rand_num_25__ETC___d262;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_uniform_rand_num_25__ETC___d253;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_tup_12_BITS_63_TO_32_ETC___d217;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_tup_12_BITS_63_TO_32_ETC___d208;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_tup_12_BITS_63_TO_32_ETC___d199;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_tup_12_BITS_63_TO_32_ETC___d190;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_tup_12_BITS_63_TO_32_ETC___d181;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_tup_12_BITS_63_TO_32_ETC___d172;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_tup_12_BITS_63_TO_32_ETC___d163;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_tup_12_BITS_63_TO_32_ETC___d154;
  tUWide DEF__0_CONCAT_0_CONCAT_IF_SEXT_tup_12_BITS_63_TO_32_ETC___d145;
  tUWide DEF_IF_cont_8_BIT_31_9_THEN_NEG_cont_8_CONCAT_0_0__ETC___d75;
  tUWide DEF_y__h46170;
  tUWide DEF_y__h46079;
  tUWide DEF_y__h45988;
  tUWide DEF_y__h45897;
  tUWide DEF_y__h45806;
  tUWide DEF_y__h45715;
  tUWide DEF_y__h45624;
  tUWide DEF_y__h45533;
  tUWide DEF_digit__h45314;
  tUWide DEF_y__h45005;
  tUWide DEF_y__h44914;
  tUWide DEF_y__h44823;
  tUWide DEF_y__h44732;
  tUWide DEF_y__h44641;
  tUWide DEF_y__h44550;
  tUWide DEF_y__h44459;
  tUWide DEF_y__h44368;
  tUWide DEF_digit__h44149;
  tUWide DEF_y__h36775;
  tUWide DEF_y__h36684;
  tUWide DEF_y__h36593;
  tUWide DEF_y__h36502;
  tUWide DEF_y__h36411;
  tUWide DEF_y__h36320;
  tUWide DEF_y__h36229;
  tUWide DEF_y__h36138;
  tUWide DEF_digit__h35919;
  tUWide DEF__0_CONCAT_IF_SEXT_mLUT_get_uniform_rand_num_25__ETC___d347;
  tUWide DEF__0_CONCAT_IF_SEXT_uniform_rand_num_25_BITS_64_T_ETC___d244;
  tUWide DEF__0_CONCAT_IF_SEXT_tup_12_BITS_63_TO_32_18_19_BI_ETC___d136;
  tUWide DEF_tx__h46109;
  tUWide DEF_tx__h46018;
  tUWide DEF_tx__h45927;
  tUWide DEF_tx__h45836;
  tUWide DEF_tx__h45745;
  tUWide DEF_tx__h45654;
  tUWide DEF_tx__h45563;
  tUWide DEF_tx__h45472;
  tUWide DEF_tx__h45381;
  tUWide DEF_tx__h44944;
  tUWide DEF_tx__h44853;
  tUWide DEF_tx__h44762;
  tUWide DEF_tx__h44671;
  tUWide DEF_tx__h44580;
  tUWide DEF_tx__h44489;
  tUWide DEF_tx__h44398;
  tUWide DEF_tx__h44307;
  tUWide DEF_tx__h44216;
  tUWide DEF_tx__h36714;
  tUWide DEF_tx__h36623;
  tUWide DEF_tx__h36532;
  tUWide DEF_tx__h36441;
  tUWide DEF_tx__h36350;
  tUWide DEF_tx__h36259;
  tUWide DEF_tx__h36168;
  tUWide DEF_tx__h36077;
  tUWide DEF_tx__h35986;
  tUWide DEF__0_CONCAT_IF_IF_cont_8_BIT_31_9_THEN_NEG_cont_8_ETC___d74;
  tUWide DEF_digit__h46020;
  tUWide DEF_digit__h45929;
  tUWide DEF_digit__h45838;
  tUWide DEF_digit__h45747;
  tUWide DEF_digit__h45656;
  tUWide DEF_digit__h45565;
  tUWide DEF_digit__h45474;
  tUWide DEF_digit__h45383;
  tUWide DEF_digit__h44855;
  tUWide DEF_digit__h44764;
  tUWide DEF_digit__h44673;
  tUWide DEF_digit__h44582;
  tUWide DEF_digit__h44491;
  tUWide DEF_digit__h44400;
  tUWide DEF_digit__h44309;
  tUWide DEF_digit__h44218;
  tUWide DEF_digit__h36625;
  tUWide DEF_digit__h36534;
  tUWide DEF_digit__h36443;
  tUWide DEF_digit__h36352;
  tUWide DEF_digit__h36261;
  tUWide DEF_digit__h36170;
  tUWide DEF_digit__h36079;
  tUWide DEF_digit__h35988;
  tUWide DEF_digit__h46111;
  tUWide DEF_digit__h44946;
  tUWide DEF_digit__h36716;
  tUWide DEF__0_CONCAT_tup_12_BITS_127_TO_96_13___d224;
 
 /* Rules */
 public:
  void RL_start_reg__dreg_update();
  void RL_state_handle_abort();
  void RL_state_fired__dreg_update();
  void RL_state_every();
  void RL_restart();
  void RL_action_l71c9();
  void RL_action_l75c9();
  void RL_action_l79c9();
  void RL_action_l83c12();
  void RL_action_l88c22();
  void RL_action_l89c22();
  void RL_action_l91c13();
  void RL_action_l95c13();
  void RL_action_l96c13();
  void RL_action_l97c22();
  void RL_action_l98c13();
  void RL_action_l99c13();
  void RL_action_l107c13();
  void RL_idle_l69c9();
  void RL_idle_l69c9_1();
  void RL_fsm_start();
  void RL_auto_start();
  void RL_auto_finish();
  void __me_check_5();
  void __me_check_6();
  void __me_check_7();
  void __me_check_8();
  void __me_check_9();
  void __me_check_10();
  void __me_check_11();
  void __me_check_12();
  void __me_check_13();
  void __me_check_14();
  void __me_check_15();
  void __me_check_16();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkBoxMullerTb &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkBoxMullerTb &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkBoxMullerTb &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkBoxMullerTb &backing);
};

#endif /* ifndef __mkBoxMullerTb_h__ */
