/*
 * Generated by Bluespec Compiler, version 2014.07.A (build 34078, 2014-07-30)
 * 
 * On Thu May  3 22:36:36 -03 2018
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkTb_h__
#define __mkTb_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkTb module */
class MOD_mkTb : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_cycle;
  MOD_Reg<tUInt32> INST_rx;
  MOD_Reg<tUInt32> INST_ry;
  MOD_Fifo<tUInt64> INST_s_fi;
  MOD_Fifo<tUInt64> INST_s_fo;
 
 /* Constructor */
 public:
  MOD_mkTb(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_RL_sink;
  tUInt8 DEF_CAN_FIRE_RL_sink;
  tUInt8 DEF_WILL_FIRE_RL_source;
  tUInt8 DEF_CAN_FIRE_RL_source;
  tUInt8 DEF_WILL_FIRE_RL_count_cycles;
  tUInt8 DEF_CAN_FIRE_RL_count_cycles;
  tUInt8 DEF_WILL_FIRE_RL_s_transform;
  tUInt8 DEF_CAN_FIRE_RL_s_transform;
  tUInt32 DEF_b__h591;
 
 /* Local definitions */
 private:
  tUInt32 DEF_signed_cycle_0___d22;
 
 /* Rules */
 public:
  void RL_s_transform();
  void RL_count_cycles();
  void RL_source();
  void RL_sink();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTb &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTb &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTb &backing);
};

#endif /* ifndef __mkTb_h__ */
